[tool.pytest.ini_options]
pythonpath = ["src", "."]
python_files = ["Test*.py", "test_*.py"]
asyncio_mode = "auto"

[tool.isort]
profile = "black"

[tool.mypy]
python_version = "3.10"
warn_return_any = true
warn_unused_configs = true
check_untyped_defs = true
plugins = ["pydantic.mypy"]

[[tool.mypy.overrides]]
module = ["transformers.*", "lumibot.*", "alpaca_trade_api.*"]
ignore_missing_imports = true

[tool.coverage.run]
source = ["src"]
